## 1-D ARRAY

In [3]:
import numpy as np 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
b = np.zeros(2)
b

array([0., 0.])

In [7]:
c = np.ones(3)
c

array([1., 1., 1.])

In [9]:
e = np.arange(5)
e

array([0, 1, 2, 3, 4])

In [11]:
f = np.arange (2,10)
f

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
g = np.arange(2,20,3)
g

array([ 2,  5,  8, 11, 14, 17])

In [17]:
h = np.linspace(0,25,num=5)
h

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [23]:
i = np.ones (5, dtype = np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [27]:
j = np.ones(5,dtype = np.float16)
j

array([1., 1., 1., 1., 1.], dtype=float16)

In [40]:
food = np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [42]:
price  = np.array([5,10,5])
price

array([ 5, 10,  5])

In [46]:
type (price)

numpy.ndarray

In [48]:
type(food)

numpy.ndarray

In [50]:
len(price)

3

In [52]:
len(food)

3

In [56]:
food[2]

'Raita'

In [58]:
price[0: ]

array([ 5, 10,  5])

In [60]:
price.mean()

6.666666666666667

## Array Functions

In [70]:
a = np.array([10,12,15,2,4,6,10,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. ,  10. , 320. ,   0.5,
        10.3])

In [74]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10. ,  10.3,  12. ,  15. ,
       320. ])

In [76]:
b = np.array([10.2,5.2,4.6,100,55.7])
b

array([ 10.2,   5.2,   4.6, 100. ,  55.7])

In [82]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10. ,  10.3,  12. ,  15. ,
       320. ,  10.2,   5.2,   4.6, 100. ,  55.7])

In [84]:
c.sort()
c

array([  0.5,   2. ,   4. ,   4.6,   5.2,   6. ,  10. ,  10. ,  10.2,
        10.3,  12. ,  15. ,  55.7, 100. , 320. ])

## 2-D ARRAY

In [29]:
np.zeros ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [35]:
np.empty ((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
c = np.arange(24).reshape (2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [88]:
a = np.array([[1,2,3], [3,4,5]])
a

array([[1, 2, 3],
       [3, 4, 5]])

In [94]:
b = np.array([[6,6,6],[9,7,8]])
b

array([[6, 6, 6],
       [9, 7, 8]])

In [98]:
c = np.concatenate((a,b))
c

array([[1, 2, 3],
       [3, 4, 5],
       [6, 6, 6],
       [9, 7, 8]])

In [106]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 6, 6],
       [9, 7, 8]])

In [108]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 6, 6, 6],
       [3, 4, 5, 9, 7, 8]])

In [110]:
b.ndim

2

## 3-D ARRAY

In [123]:
a = np.array([[[5,6,7],[8,9,10]],
                [[1,2,3],[4,5,6]],
                [[5,5,5],[3,3,3]]])
a

array([[[ 5,  6,  7],
        [ 8,  9, 10]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  5,  5],
        [ 3,  3,  3]]])

In [125]:
 a.ndim

3

In [127]:
b = np.array([[[2,6,2],[8,1,1]],
                [[1,1,3],[4,4,6]],
                [[5,8,7],[3,1,3]]])
b

array([[[2, 6, 2],
        [8, 1, 1]],

       [[1, 1, 3],
        [4, 4, 6]],

       [[5, 8, 7],
        [3, 1, 3]]])

In [133]:
c= np.concatenate((a,b))
c

array([[[ 5,  6,  7],
        [ 8,  9, 10]],

       [[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 5,  5,  5],
        [ 3,  3,  3]],

       [[ 2,  6,  2],
        [ 8,  1,  1]],

       [[ 1,  1,  3],
        [ 4,  4,  6]],

       [[ 5,  8,  7],
        [ 3,  1,  3]]])

In [135]:
np.concatenate((a,b),axis=1)

array([[[ 5,  6,  7],
        [ 8,  9, 10],
        [ 2,  6,  2],
        [ 8,  1,  1]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 1,  1,  3],
        [ 4,  4,  6]],

       [[ 5,  5,  5],
        [ 3,  3,  3],
        [ 5,  8,  7],
        [ 3,  1,  3]]])

In [137]:
type(c)

numpy.ndarray

In [139]:
c.ndim

3

In [141]:
c.size

36

In [143]:
c.shape

(6, 2, 3)

In [151]:
d = np.arange(4)
d

array([0, 1, 2, 3])

In [155]:
e = d.reshape(2,2)
e

array([[0, 1],
       [2, 3]])

## Convert 1-d into 2-d

In [158]:
a = np.array([1,2,3,4,5,6,7,8,9])
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
a.shape

(9,)

In [174]:
#Row wise
b = a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [166]:
b.shape

(1, 9)

In [172]:
#Column wise
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [170]:
c.shape

(9, 1)

In [178]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
a*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [184]:
a.sum()

45

In [188]:
c.sum()

45

In [190]:
b.mean()

5.0