# Task 1
> 1-D Array Sum of Evem And Odd Index Elements 

In [7]:
import numpy as np

def sumOfIndex(array):
    sumEven=0
    sumOdd=0
    i=0
    while i < len(array):
        if i % 2 == 0:
            #It is even
            sumEven=sumEven+array[i]
        else:
            #It is Odd
            sumOdd=sumOdd+array[i]
        i = i+1
    
    print("Sum Of Even Indexed Numbers Is: ",sumEven)
    print("Sum Of Odd Indexed Numbers Is: ",sumOdd)

array = np.array([2,5,3,8,10,7])
print('Input Array: ',array)
sumOfIndex(array=array)


Input Array:  [ 2  5  3  8 10  7]
Sum Of Even Indexed Numbers Is:  15
Sum Of Odd Indexed Numbers Is:  20


# Task 2
> Find Maximum Score In Each Row Of 2-D Array

In [4]:
import numpy as np

def maxIneachRow(array):
    print('Highest Score In Each Row Is: ',array.max(axis=1)) # AXIS 1 TO GET ROW WISE . BY DEFAULT IT IS 0 MEANS COLUMN WISE

array = np.array([[65,78,85,92,55],
                  [82,91,88,60,70],
                  [95,80,75,88,72]])


print('Input Array: ',array)
maxIneachRow(array=array)

Input Array:  [[65 78 85 92 55]
 [82 91 88 60 70]
 [95 80 75 88 72]]
Highest Score In Each Row Is:  [92 91 95]


# Task 3
> Sum Of Diagnols In A 3-D Matrix

In [3]:
import numpy as np

def sumOfDiagnols(array):
    sum=0
    for i in range(len(array)):
        for j in range(len(array[i])):
            for k in range(len(array[i][j])):
                if(i==j==k):
                    print(array[i][j][k])
                    sum=array[i][j][k]+sum
    return sum

array = np.array([
    [[1,2,3],[4,5,6],[7,8,9]]
    ,[[10,11,12],[13,14,15],[16,17,18]],
    [[19,20,21],[22,23,24],[25,26,27]]])

print("Input Array: ",array)
print("Sum Of Diagnols Is: ",sumOfDiagnols(array=array))

Input Array:  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
1
14
27
Sum Of Diagnols Is:  42
