In [9]:
import numpy as np

def sum(arr):
    even_sum = 0
    odd_sum = 0

    for i in range(len(arr)):  
        if i % 2 == 0:  
            even_sum += arr[i]
        else:  
            odd_sum += arr[i]

    return even_sum, odd_sum

arr = np.array([2, 5, 3, 8, 10, 7])
even_sum, odd_sum = sum(arr)

print(f"Sum of elements at even indices = {even_sum}")
print(f"Sum of elements at odd indices = {odd_sum}")


Sum of elements at even indices = 15
Sum of elements at odd indices = 20


In [10]:
import numpy as np

arr = np.array([[65, 78, 85, 92, 55],   # Student 1
[82, 91, 88, 60, 70],   # Student 2
[95, 80, 75, 88, 72]])   # Student 3
max_value = arr.max(axis=1)
print("Maximum values per row:", max_value)


Maximum values per row: [92 91 95]


In [17]:
import numpy as np
arr = np.array([
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

print("Matrices are:") 
print(arr) 
  
diag = np.diagonal(arr) 
  
print("\nDiagonal elements are:") 
print(diag) 
  
print("\nSum of Diagonal elements:") 
print(sum(diag)) 



Matrices are:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Diagonal elements are:
[[ 1 13 25]
 [ 2 14 26]
 [ 3 15 27]]

Sum of Diagonal elements is:
(array([ 4, 28, 52]), array([ 2, 14, 26]))
